title: David Bindel
email: bindel@cornell.edu
description: Numerical Methods for Data Science
baseurl: ""
url: "http://www.cs.cornell.edu/~bindel/class/sjtu-summer19"

encoding: utf-8
timezone: America/New_York

exclude: ["Rakefile"]

markdown: kramdown
